using Microsoft.Xrm.Sdk;
using System;
using System.Collections.Generic;

namespace WorkOrderVirtualEntity.Models
{
    public class CommonModels
    {
    }
    public class IncidentRequest
    {
        public string JobId { get; set; }
        public string IncidentId { get; set; }
        public int PageNo { get; set; }
        public int Size { get; set; }
    }
    public class IncidentResponse

    {
        public List<dtoIncidents> incident { get; set; }
        public bool success { get; set; }
        public string error { get; set; }
    }
    public class dtoIncidents
    {
        public string createdby { get; set; }
        public string createdbyname { get; set; }
        public string createdbyyominame { get; set; }
        public string createdon { get; set; }
        public string createdonbehalfby { get; set; }
        public string createdonbehalfbyname { get; set; }
        public string createdonbehalfbyyominame { get; set; }
        public string hil_customer { get; set; }
        public string hil_customeridtype { get; set; }
        public string hil_customername { get; set; }
        public string hil_customeryominame { get; set; }
        public int? hil_inputwatertds { get; set; }
        public bool? hil_iswarrantyvoid { get; set; }
        public string hil_iswarrantyvoidname { get; set; }
        public string hil_modelcode { get; set; }
        public string hil_modelcodename { get; set; }
        public string hil_modeldescription { get; set; }
        public string hil_modelname { get; set; }
        public string hil_natureofcomplaint { get; set; }
        public string hil_natureofcomplaintname { get; set; }
        public string hil_noofpeopleinhome { get; set; }
        public string hil_observation { get; set; }
        public string hil_observationname { get; set; }
        public string hil_ph { get; set; }
        public string hil_productcategory { get; set; }
        public string hil_productcategoryname { get; set; }
        public int? hil_productreplacement { get; set; }
        public string hil_productreplacementname { get; set; }
        public string hil_productsubcategory { get; set; }
        public string hil_productsubcategoryname { get; set; }
        public int? hil_purewatertds { get; set; }
        public int? hil_quantity { get; set; }
        public int? hil_rejectwatertds { get; set; }
        public string hil_serialnumber { get; set; }
        public double? hil_tds { get; set; }
        public int? hil_warrantystatus { get; set; }
        public string hil_warrantystatusname { get; set; }
        public string hil_warrantyvoidreasoncode { get; set; }
        public int? hil_watersource { get; set; }
        public string hil_watersourcename { get; set; }
        public int? hil_waterstoragetype { get; set; }
        public string hil_waterstoragetypename { get; set; }
        public int? importsequencenumber { get; set; }
        public string modifiedby { get; set; }
        public string modifiedbyname { get; set; }
        public string modifiedbyyominame { get; set; }
        public string modifiedon { get; set; }
        public string modifiedonbehalfby { get; set; }
        public string modifiedonbehalfbyname { get; set; }
        public string modifiedonbehalfbyyominame { get; set; }
        public string msdyn_agreementbookingincident { get; set; }
        public string msdyn_agreementbookingincidentname { get; set; }
        public string msdyn_customerasset { get; set; }
        public string msdyn_customerassetname { get; set; }
        public string msdyn_description { get; set; }
        public int? msdyn_estimatedduration { get; set; }
        public bool? msdyn_incidentresolved { get; set; }
        public string msdyn_incidentresolvedname { get; set; }
        public string msdyn_incidenttype { get; set; }
        public string msdyn_incidenttypename { get; set; }
        public string msdyn_internalflags { get; set; }
        public bool? msdyn_ismobile { get; set; }
        public string msdyn_ismobilename { get; set; }
        public bool? msdyn_isprimary { get; set; }
        public string msdyn_isprimaryname { get; set; }
        public bool? msdyn_itemspopulated { get; set; }
        public string msdyn_itemspopulatedname { get; set; }
        public string msdyn_name { get; set; }
        public string msdyn_resourcerequirement { get; set; }
        public string msdyn_resourcerequirementname { get; set; }
        public float? msdyn_taskspercentcompleted { get; set; }
        public string msdyn_workorder { get; set; }
        public string msdyn_workorderincidentid { get; set; }
        public string msdyn_workordername { get; set; }
        public string new_warrantyenddate { get; set; }
        public string overriddencreatedon { get; set; }
        public string ownerid { get; set; }
        public string owneridname { get; set; }
        public string owneridtype { get; set; }
        public string owneridyominame { get; set; }
        public string owningbusinessunit { get; set; }
        public string owningteam { get; set; }
        public string owninguser { get; set; }
        public int? statecode { get; set; }
        public string statecodename { get; set; }
        public int? statuscode { get; set; }
        public string statuscodename { get; set; }
        public int? timezoneruleversionnumber { get; set; }
        public int? utcconversiontimezonecode { get; set; }
        public Int64? versionnumber { get; set; }
        public string CreatedDateWh { get; set; }
    }
    public class IntegrationConfiguration
    {
        public string url { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
    }
    public class ArchivedJobsResponse
    {
        public List<dtoWorkOrders> workOrders { get; set; }
        public bool success { get; set; }
        public object error { get; set; }
    }
    public class dtoWorkOrders
    {
        public string createdby { get; set; }
        public string createdbyname { get; set; }
        public string createdbyyominame { get; set; }
        public string createdon { get; set; }
        public string createdonbehalfby { get; set; }
        public string createdonbehalfbyname { get; set; }
        public string createdonbehalfbyyominame { get; set; }
        public string entityimage { get; set; }
        public string entityimage_timestamp { get; set; }
        public string entityimage_url { get; set; }
        public string entityimageid { get; set; }
        public double? exchangerate { get; set; }
        public string hil_05 { get; set; }
        public double? hil_actualcharges { get; set; }
        public double? hil_actualcharges_base { get; set; }
        public string hil_address { get; set; }
        public string hil_addressdetails { get; set; }
        public string hil_addressname { get; set; }
        public string hil_agebucket { get; set; }
        public string hil_agebucketname { get; set; }
        public int? hil_ageing { get; set; }
        public string hil_allocatebykpi { get; set; }
        public string hil_allocatebykpiname { get; set; }
        public string hil_alternate { get; set; }
        public int? hil_appointmentcount { get; set; }
        public String hil_appointmentcount_date { get; set; }
        public int? hil_appointmentcount_state { get; set; }
        public bool? hil_appointmentmandatory { get; set; }
        public string hil_appointmentmandatoryname { get; set; }
        public String hil_appointmentseton { get; set; }
        public int? hil_appointmentstatus { get; set; }
        public string hil_appointmentstatusname { get; set; }
        public String hil_appointmenttime { get; set; }
        public string hil_area { get; set; }
        public string hil_areaname { get; set; }
        public string hil_areatext { get; set; }
        public string hil_assignedon { get; set; }
        public string hil_assignmentdate { get; set; }
        public string hil_assignmentmatrix { get; set; }
        public string hil_assignmentmatrixname { get; set; }
        public string hil_assigntobranchhead { get; set; }
        public string hil_assigntobranchheadname { get; set; }
        public bool? hil_assigntome { get; set; }
        public string hil_assigntomename { get; set; }
        public string hil_associateddealer { get; set; }
        public string hil_associateddealername { get; set; }
        public string hil_associateddealeryominame { get; set; }
        public int? hil_automaticassign { get; set; }
        public string hil_automaticassignname { get; set; }
        public string hil_branch { get; set; }
        public string hil_branchengineercity { get; set; }
        public string hil_branchheadapproval { get; set; }
        public string hil_branchheadapprovalname { get; set; }
        public string hil_branchname { get; set; }
        public string hil_branchtext { get; set; }
        public int? hil_brand { get; set; }
        public string hil_brandname { get; set; }
        public string hil_bsh { get; set; }
        public string hil_bshname { get; set; }
        public string hil_bshyominame { get; set; }
        public string hil_bucket { get; set; }
        public int? hil_bucket_ageing { get; set; }
        public bool? hil_calculatecharges { get; set; }
        public string hil_calculatechargesname { get; set; }
        public int? hil_callertype { get; set; }
        public string hil_callertypename { get; set; }
        public string hil_callingnumber { get; set; }
        public string hil_callsubtype { get; set; }
        public string hil_callsubtypename { get; set; }
        public string hil_calltype { get; set; }
        public string hil_calltypename { get; set; }
        public string hil_cancellationdate { get; set; }
        public string hil_characterstics { get; set; }
        public string hil_charactersticsname { get; set; }
        public string hil_chequedate { get; set; }
        public string hil_chequenumber { get; set; }
        public string hil_city { get; set; }
        public string hil_cityname { get; set; }
        public string hil_citytext { get; set; }
        public string hil_claimheader { get; set; }
        public string hil_claimheadername { get; set; }
        public string hil_claimline { get; set; }
        public string hil_claimlinename { get; set; }
        public bool? hil_closeticket { get; set; }
        public string hil_closeticketname { get; set; }
        public string hil_closureremarks { get; set; }
        public int? hil_countryclassification { get; set; }
        public string hil_countryclassificationname { get; set; }
        public string hil_customercomplaintdescription { get; set; }
        public int? hil_customerfeedback { get; set; }
        public string hil_customerfeedbackname { get; set; }
        public string hil_customername { get; set; }
        public string hil_customerref { get; set; }
        public string hil_customerrefidtype { get; set; }
        public string hil_customerrefname { get; set; }
        public string hil_customerrefyominame { get; set; }
        public bool? hil_delinkpo { get; set; }
        public string hil_delinkponame { get; set; }
        public string hil_district { get; set; }
        public string hil_districtname { get; set; }
        public string hil_districttext { get; set; }
        public string hil_email { get; set; }
        public string hil_emailcustomer { get; set; }
        public string hil_emailcustomername { get; set; }
        public string hil_emailcustomeryominame { get; set; }
        public string hil_emergencycall { get; set; }
        public string hil_emergencycallname { get; set; }
        public string hil_emergencyremarks { get; set; }
        public string hil_emolpyeenamecode { get; set; }
        public string hil_escalationcall { get; set; }
        public string hil_escalationcallname { get; set; }
        public int? hil_escalationcount { get; set; }
        public String hil_escalationcount_date { get; set; }
        public int? hil_escalationcount_state { get; set; }
        public string hil_escallationcountinteger { get; set; }
        public bool? hil_estimatecharges { get; set; }
        public string hil_estimatechargesname { get; set; }
        public string hil_estimatechargestotal { get; set; }
        public string hil_estimatechargestotal_base { get; set; }
        public string hil_estimatedchargedecimal { get; set; }
        public string hil_firstresponsein { get; set; }
        public string hil_firstresponseinname { get; set; }
        public String hil_firstresponseon { get; set; }
        public bool? hil_flagpo { get; set; }
        public string hil_flagponame { get; set; }
        public string hil_fulladdress { get; set; }
        public string hil_ifamceligible { get; set; }
        public string hil_ifamceligiblename { get; set; }
        public bool? hil_ifclosedjob { get; set; }
        public string hil_ifclosedjobname { get; set; }
        public bool? hil_ifparametersadded { get; set; }
        public string hil_ifparametersaddedname { get; set; }
        public int? hil_incidentquantity { get; set; }
        public bool? hil_ischargable { get; set; }
        public string hil_ischargablename { get; set; }
        public string hil_ischargeable { get; set; }
        public string hil_ischargeablename { get; set; }
        public string hil_isclaimable { get; set; }
        public string hil_isclaimablename { get; set; }
        public bool? hil_isocr { get; set; }
        public string hil_isocrname { get; set; }
        public string hil_iswrongjobclosure { get; set; }
        public string hil_iswrongjobclosurename { get; set; }
        public string hil_jobcancelreason { get; set; }
        public string hil_jobcancelreasonname { get; set; }
        public string hil_jobclass { get; set; }
        public string hil_jobclassapproval { get; set; }
        public string hil_jobclassapprovalname { get; set; }
        public string hil_jobclassname { get; set; }
        public bool? hil_jobclosemobile { get; set; }
        public string hil_jobclosemobilename { get; set; }
        public string hil_jobclosureby { get; set; }
        public string hil_jobclosurebyname { get; set; }
        public string hil_jobclosurebyyominame { get; set; }
        public String hil_jobclosuredon { get; set; }
        public String hil_jobclosureon { get; set; }
        public int? hil_jobincidentcount { get; set; }
        public int? hil_jobpriority { get; set; }
        public string hil_jobstatuscode { get; set; }
        public string hil_kkgcode { get; set; }
        public string hil_kkgcode_sms { get; set; }
        public string hil_kkgcode_smsname { get; set; }
        public string hil_kkgotp { get; set; }
        public bool? hil_kkgprovided { get; set; }
        public string hil_kkgprovidedname { get; set; }
        public String hil_lastresponsetime { get; set; }
        public string hil_locationofasset { get; set; }
        public string hil_locationofassetname { get; set; }
        public double? hil_maxquantity { get; set; }
        public double? hil_minquantity { get; set; }
        public string hil_mobilenumber { get; set; }
        public string hil_modelid { get; set; }
        public string hil_modelname { get; set; }
        public string hil_modeofpayment { get; set; }
        public string hil_modeofpaymentname { get; set; }
        public string hil_natureofcomplaint { get; set; }
        public string hil_natureofcomplaintname { get; set; }
        public string hil_newserialnumber { get; set; }
        public string hil_nsh { get; set; }
        public string hil_nshname { get; set; }
        public string hil_nshyominame { get; set; }
        public string hil_observation { get; set; }
        public string hil_observationname { get; set; }
        public string hil_onbehalfofdealer { get; set; }
        public string hil_onbehalfofdealername { get; set; }
        public string hil_onbehalfofdealeryominame { get; set; }
        public string hil_owneraccount { get; set; }
        public string hil_owneraccountname { get; set; }
        public string hil_owneraccountyominame { get; set; }
        public double? hil_payblechargedecimal { get; set; }
        public string hil_pendingquantity { get; set; }
        public int? hil_phonecallcount { get; set; }
        public string hil_pincode { get; set; }
        public string hil_pincodename { get; set; }
        public string hil_pincodetext { get; set; }
        public string hil_pmscount { get; set; }
        public string hil_pmsdate { get; set; }
        public string hil_preferreddate { get; set; }
        public string hil_preferredtime { get; set; }
        public string hil_preferredtimename { get; set; }
        public string hil_preferredtimeofvisit { get; set; }
        public string hil_productcategory { get; set; }
        public string hil_productcategoryname { get; set; }
        public string hil_productcatsubcatmapping { get; set; }
        public string hil_productcatsubcatmappingname { get; set; }
        public string hil_productreplacement { get; set; }
        public string hil_productreplacementname { get; set; }
        public string hil_productsubcategory { get; set; }
        public string hil_productsubcategorycallsubtype { get; set; }
        public string hil_productsubcategoryname { get; set; }
        public String hil_purchasedate { get; set; }
        public string hil_purchasedfrom { get; set; }
        public int? hil_quantity { get; set; }
        public string hil_quantityofunits { get; set; }
        public string hil_receiptamount { get; set; }
        public string hil_receiptamount_base { get; set; }
        public string hil_receiptnumber { get; set; }
        public string hil_regardingemail { get; set; }
        public string hil_regardingemailname { get; set; }
        public string hil_regardingfallback { get; set; }
        public string hil_regardingfallbackname { get; set; }
        public string hil_region { get; set; }
        public string hil_regionbranch { get; set; }
        public string hil_regionname { get; set; }
        public string hil_regiontext { get; set; }
        public int? hil_remaindercount { get; set; }
        public String hil_remaindercount_date { get; set; }
        public int? hil_remaindercount_state { get; set; }
        public string hil_remaindercountinteger { get; set; }
        public string hil_remindercall { get; set; }
        public string hil_remindercallname { get; set; }
        public string hil_repairdone { get; set; }
        public string hil_repairdonename { get; set; }
        public string hil_reportbinary { get; set; }
        public string hil_reporttext { get; set; }
        public int? hil_requesttype { get; set; }
        public string hil_requesttypename { get; set; }
        public bool? hil_resendkkg { get; set; }
        public string hil_resendkkgname { get; set; }
        public string hil_resolvebykpi { get; set; }
        public string hil_resolvebykpiname { get; set; }
        public string hil_returned { get; set; }
        public string hil_returnedname { get; set; }
        public string hil_salesoffice { get; set; }
        public string hil_salesofficename { get; set; }
        public int? hil_salutation { get; set; }
        public string hil_salutationname { get; set; }
        public bool? hil_sendestimate { get; set; }
        public string hil_sendestimatename { get; set; }
        public bool? hil_sendtcr { get; set; }
        public string hil_sendtcrname { get; set; }
        public string hil_serviceaddress { get; set; }
        public string hil_serviceaddressname { get; set; }
        public string hil_slastarton { get; set; }
        public int? hil_slastatus { get; set; }
        public string hil_slastatusname { get; set; }
        public int? hil_sourceofjob { get; set; }
        public string hil_sourceofjobname { get; set; }
        public string hil_state { get; set; }
        public string hil_statename { get; set; }
        public string hil_statetext { get; set; }
        public string hil_systemremarks { get; set; }
        public string hil_technicianname { get; set; }
        public double? hil_timeinappointmentdate { get; set; }
        public double? hil_timeincurrentdate { get; set; }
        public double? hil_timeinfirstresponse { get; set; }
        public double? hil_timeinjobclosure { get; set; }
        public string hil_town { get; set; }
        public string hil_townname { get; set; }
        public string hil_typeofassignee { get; set; }
        public string hil_typeofassigneename { get; set; }
        public int? hil_warrantystatus { get; set; }
        public string hil_warrantystatusname { get; set; }
        public string hil_webclosureremarks { get; set; }
        public string hil_workdoneby { get; set; }
        public string hil_workdonebyname { get; set; }
        public string hil_workdonebyyominame { get; set; }
        public bool? hil_workstarted { get; set; }
        public string hil_workstartedname { get; set; }
        public string importsequencenumber { get; set; }
        public string lastonholdtime { get; set; }
        public string modifiedby { get; set; }
        public string modifiedbyname { get; set; }
        public string modifiedbyyominame { get; set; }
        public String modifiedon { get; set; }
        public string modifiedonbehalfby { get; set; }
        public string modifiedonbehalfbyname { get; set; }
        public string modifiedonbehalfbyyominame { get; set; }
        public string msdyn_address1 { get; set; }
        public string msdyn_address2 { get; set; }
        public string msdyn_address3 { get; set; }
        public string msdyn_addressname { get; set; }
        public string msdyn_agreement { get; set; }
        public string msdyn_agreementname { get; set; }
        public string msdyn_billingaccount { get; set; }
        public string msdyn_billingaccountname { get; set; }
        public string msdyn_billingaccountyominame { get; set; }
        public string msdyn_bookingsummary { get; set; }
        public string msdyn_childindex { get; set; }
        public string msdyn_city { get; set; }
        public string msdyn_closedby { get; set; }
        public string msdyn_closedbyname { get; set; }
        public string msdyn_closedbyyominame { get; set; }
        public string msdyn_country { get; set; }
        public string msdyn_customerasset { get; set; }
        public string msdyn_customerassetname { get; set; }
        public string msdyn_datewindowend { get; set; }
        public string msdyn_datewindowstart { get; set; }
        public double? msdyn_estimatesubtotalamount { get; set; }
        public double? msdyn_estimatesubtotalamount_base { get; set; }
        public string msdyn_followupnote { get; set; }
        public bool? msdyn_followuprequired { get; set; }
        public string msdyn_followuprequiredname { get; set; }
        public string msdyn_instructions { get; set; }
        public string msdyn_internalflags { get; set; }
        public bool? msdyn_isfollowup { get; set; }
        public string msdyn_isfollowupname { get; set; }
        public bool? msdyn_ismobile { get; set; }
        public string msdyn_ismobilename { get; set; }
        public string msdyn_latitude { get; set; }
        public string msdyn_longitude { get; set; }
        public string msdyn_name { get; set; }
        public string msdyn_opportunityid { get; set; }
        public string msdyn_opportunityidname { get; set; }
        public string msdyn_parentworkorder { get; set; }
        public string msdyn_parentworkordername { get; set; }
        public string msdyn_postalcode { get; set; }
        public string msdyn_preferredresource { get; set; }
        public string msdyn_preferredresourcename { get; set; }
        public string msdyn_pricelist { get; set; }
        public string msdyn_pricelistname { get; set; }
        public string msdyn_primaryincidentdescription { get; set; }
        public string msdyn_primaryincidentestimatedduration { get; set; }
        public string msdyn_primaryincidenttype { get; set; }
        public string msdyn_primaryincidenttypename { get; set; }
        public string msdyn_priority { get; set; }
        public string msdyn_priorityname { get; set; }
        public string msdyn_reportedbycontact { get; set; }
        public string msdyn_reportedbycontactname { get; set; }
        public string msdyn_reportedbycontactyominame { get; set; }
        public string msdyn_serviceaccount { get; set; }
        public string msdyn_serviceaccountname { get; set; }
        public string msdyn_serviceaccountyominame { get; set; }
        public string msdyn_servicerequest { get; set; }
        public string msdyn_servicerequestname { get; set; }
        public string msdyn_serviceterritory { get; set; }
        public string msdyn_serviceterritoryname { get; set; }
        public string msdyn_stateorprovince { get; set; }
        public string msdyn_substatus { get; set; }
        public string msdyn_substatusname { get; set; }
        public double? msdyn_subtotalamount { get; set; }
        public double? msdyn_subtotalamount_base { get; set; }
        public string msdyn_supportcontact { get; set; }
        public string msdyn_supportcontactname { get; set; }
        public int? msdyn_systemstatus { get; set; }
        public string msdyn_systemstatusname { get; set; }
        public bool? msdyn_taxable { get; set; }
        public string msdyn_taxablename { get; set; }
        public string msdyn_taxcode { get; set; }
        public string msdyn_taxcodename { get; set; }
        public String msdyn_timeclosed { get; set; }
        public String msdyn_timefrompromised { get; set; }
        public string msdyn_timegroup { get; set; }
        public string msdyn_timegroupdetailselected { get; set; }
        public string msdyn_timegroupdetailselectedname { get; set; }
        public string msdyn_timegroupname { get; set; }
        public string msdyn_timetopromised { get; set; }
        public string msdyn_timewindowend { get; set; }
        public string msdyn_timewindowstart { get; set; }
        public double? msdyn_totalamount { get; set; }
        public double? msdyn_totalamount_base { get; set; }
        public double? msdyn_totalsalestax { get; set; }
        public double? msdyn_totalsalestax_base { get; set; }
        public string msdyn_worklocation { get; set; }
        public string msdyn_worklocationname { get; set; }
        public string msdyn_workorderid { get; set; }
        public string msdyn_workordersummary { get; set; }
        public string msdyn_workordertype { get; set; }
        public string msdyn_workordertypename { get; set; }
        public string new_owner_temp { get; set; }
        public string new_owner_tempname { get; set; }
        public string new_owner_tempyominame { get; set; }
        public string onholdtime { get; set; }
        public string overriddencreatedon { get; set; }
        public string ownerid { get; set; }
        public string owneridname { get; set; }
        public string owneridtype { get; set; }
        public string owneridyominame { get; set; }
        public string owningbusinessunit { get; set; }
        public string owningteam { get; set; }
        public string owninguser { get; set; }
        public string processid { get; set; }
        public string slaid { get; set; }
        public string slaidname { get; set; }
        public string slainvokedid { get; set; }
        public string slainvokedidname { get; set; }
        public string stageid { get; set; }
        public int? statecode { get; set; }
        public string statecodename { get; set; }
        public int? statuscode { get; set; }
        public string statuscodename { get; set; }
        public int? timezoneruleversionnumber { get; set; }
        public string transactioncurrencyid { get; set; }
        public string transactioncurrencyidname { get; set; }
        public string traversedpath { get; set; }
        public string utcconversiontimezonecode { get; set; }
        public long? versionnumber { get; set; }
        public String CreatedDateWH { get; set; }
    }
    public class JobArchived
    {
        public Decimal hil_actualcharges { get; set; }
        public Decimal hil_actualcharges_Base { get; set; }
        public OptionSetValue hil_AdditionalAction { get; set; }
        public EntityReference hil_Address { get; set; }
        public String hil_AddressName { get; set; }
        public EntityReference hil_AllocateByKPI { get; set; }
        public String hil_AllocateByKPIName { get; set; }
        public OptionSetValue hil_AMCSyncStatus { get; set; }
        public DateTime hil_AppointmentCount_Date { get; set; }
        public int hil_AppointmentCount_State { get; set; }
        public Boolean hil_ArchiveLog { get; set; }
        public EntityReference hil_area { get; set; }
        public String hil_areaName { get; set; }
        public String hil_AreaText { get; set; }
        public EntityReference hil_AssignmentMatrix { get; set; }
        public String hil_AssignmentMatrixName { get; set; }
        public OptionSetValue hil_AssigntoBranchHead { get; set; }
        public Boolean hil_Assigntome { get; set; }
        public EntityReference hil_associateddealer { get; set; }
        public String hil_associateddealerName { get; set; }
        public String hil_associateddealerYomiName { get; set; }
        public String hil_b2bcompanyname { get; set; }
        public Decimal hil_BalanceAmount { get; set; }
        public Decimal hil_balanceamount_Base { get; set; }
        public String hil_BookingSummary { get; set; }
        public EntityReference hil_Branch { get; set; }
        public String hil_BranchEngineerCity { get; set; }
        public String hil_BranchName { get; set; }
        public String hil_BranchText { get; set; }
        public EntityReference hil_BSH { get; set; }
        public String hil_BSHName { get; set; }
        public String hil_BSHYomiName { get; set; }
        public OptionSetValue hil_CallCenter { get; set; }
        public OptionSetValue hil_CallerType { get; set; }
        public EntityReference hil_CallSubType { get; set; }
        public String hil_CallSubTypeName { get; set; }
        public EntityReference hil_CallType { get; set; }
        public String hil_CallTypeName { get; set; }
        public EntityReference hil_CancelledBy { get; set; }
        public String hil_CancelledByName { get; set; }
        public String hil_CancelledByYomiName { get; set; }
        public Boolean hil_CancelTicket { get; set; }
        public OptionSetValue hil_ChannelPartnerCategory { get; set; }
        public EntityReference hil_Characterstics { get; set; }
        public String hil_CharactersticsName { get; set; }
        public DateTime hil_chequedate { get; set; }
        public String hil_chequenumber { get; set; }
        public int hil_ChildIndex { get; set; }
        public EntityReference hil_City { get; set; }
        public String hil_CityName { get; set; }
        public String hil_CityText { get; set; }
        public Decimal hil_ClaimAmount { get; set; }
        public Decimal hil_claimamount_Base { get; set; }
        public EntityReference hil_ClaimHeader { get; set; }
        public String hil_ClaimHeaderName { get; set; }
        public EntityReference hil_ClaimLine { get; set; }
        public String hil_ClaimLineName { get; set; }
        public OptionSetValue hil_ClaimStatus { get; set; }
        public Boolean hil_CloseTicket { get; set; }
        public String hil_ClosureRemarks { get; set; }
        public EntityReference hil_consumercategory { get; set; }
        public String hil_consumercategoryName { get; set; }
        public EntityReference hil_consumertype { get; set; }
        public String hil_consumertypeName { get; set; }
        public String hil_country { get; set; }
        public Boolean hil_CreateChildJob { get; set; }
        public EntityReference hil_createdby { get; set; }
        public String hil_createdbyName { get; set; }
        public String hil_createdbyYomiName { get; set; }
        public DateTime hil_CreatedOn { get; set; }
        public EntityReference hil_createdonbehalfby { get; set; }
        public String hil_createdonbehalfbyName { get; set; }
        public String hil_createdonbehalfbyYomiName { get; set; }
        public OptionSetValue hil_CustomerCareNumber { get; set; }
        public String hil_CustomerComplaintDescription { get; set; }
        public OptionSetValue hil_customerfeedback { get; set; }
        public String hil_customername { get; set; }
        public EntityReference hil_CustomerRef { get; set; }
        public EntityReference hil_CustomerRef_account { get; set; }
        public String hil_CustomerRef_accountName { get; set; }
        public String hil_CustomerRef_accountYomiName { get; set; }
        public EntityReference hil_CustomerRef_contact { get; set; }
        public String hil_CustomerRef_contactName { get; set; }
        public String hil_CustomerRef_contactYomiName { get; set; }
        public DateTime hil_DateWindowEnd { get; set; }
        public DateTime hil_DateWindowStart { get; set; }
        public String hil_DiscountCouponCode { get; set; }
        public EntityReference hil_district { get; set; }
        public String hil_districtName { get; set; }
        public String hil_Email { get; set; }
        public EntityReference hil_EmailCustomer { get; set; }
        public String hil_EmailCustomerName { get; set; }
        public String hil_EmailCustomerYomiName { get; set; }
        public OptionSetValue hil_emergencycall { get; set; }
        public String hil_emergencyremarks { get; set; }
        public String hil_EmolpyeeNameCode { get; set; }
        public OptionSetValue hil_escalationcall { get; set; }
        public DateTime hil_EscalationCount_Date { get; set; }
        public int hil_EscalationCount_State { get; set; }
        public int hil_EscallationCountint { get; set; }
        public Decimal hil_estimatechargestotal_Base { get; set; }
        public Decimal hil_EstimatedChargeDecimal { get; set; }
        public Decimal hil_EstimateSubtotalAmount { get; set; }
        public Decimal hil_estimatesubtotalamount_Base { get; set; }
        public Decimal hil_ExchangeRate { get; set; }
        public DateTime hil_ExpecteddeliveryDate { get; set; }
        public EntityReference hil_FirstResponseIn { get; set; }
        public String hil_FirstResponseInName { get; set; }
        public EntityReference hil_FiscalMonth { get; set; }
        public String hil_FiscalMonthName { get; set; }
        public String hil_FollowUpNote { get; set; }
        public Boolean hil_FollowUpRequired { get; set; }
        public Boolean hil_GenerateClaim { get; set; }
        public OptionSetValue hil_IfAMCEligible { get; set; }
        public Boolean hil_IfParametersAdded { get; set; }
        public int hil_ImportSequenceNumber { get; set; }
        public String hil_Instructions { get; set; }
        public String hil_InternalFlags { get; set; }
        public Boolean hil_ischargable { get; set; }
        public OptionSetValue hil_IsChargeable { get; set; }
        public OptionSetValue hil_IsClaimable { get; set; }
        public Boolean hil_IsFollowUp { get; set; }
        public Boolean hil_isgascharged { get; set; }
        public Boolean hil_IsMobile { get; set; }
        public Boolean hil_IsOCR { get; set; }
        public OptionSetValue hil_IsWrongJobClosure { get; set; }
        public OptionSetValue hil_JobCancelReason { get; set; }
        public OptionSetValue hil_JobClass { get; set; }
        public EntityReference hil_JobClosureBy { get; set; }
        public String hil_JobClosureByName { get; set; }
        public String hil_JobClosureByYomiName { get; set; }
        public int hil_JobClosureCounter { get; set; }
        public DateTime hil_JobClosuredon { get; set; }
        public DateTime hil_JobClosureOn { get; set; }
        public int hil_JobIncidentCount { get; set; }
        public OptionSetValue hil_JobReopenReason { get; set; }
        public Guid hil_jobsarchivedId { get; set; }
        public String hil_kkgcode { get; set; }
        public OptionSetValue hil_KKGcode_sms { get; set; }
        public String hil_KKGOTP { get; set; }
        public Boolean hil_LaborInWarranty { get; set; }
        public DateTime hil_LastOnHoldTime { get; set; }
        public DateTime hil_LastResponseTime { get; set; }
        public Double hil_Latitude { get; set; }
        public Double hil_Longitude { get; set; }
        public Decimal hil_MaxQuantity { get; set; }
        public Decimal hil_MinQuantity { get; set; }
        public String hil_mobilenumber { get; set; }
        public String hil_modelid { get; set; }
        public EntityReference hil_modifiedby { get; set; }
        public String hil_modifiedbyName { get; set; }
        public String hil_modifiedbyYomiName { get; set; }
        public DateTime hil_ModifiedOn { get; set; }
        public EntityReference hil_modifiedonbehalfby { get; set; }
        public String hil_modifiedonbehalfbyName { get; set; }
        public String hil_modifiedonbehalfbyYomiName { get; set; }
        public String hil_name { get; set; }
        public EntityReference hil_natureofcomplaint { get; set; }
        public String hil_natureofcomplaintName { get; set; }
        public EntityReference hil_new_Owner_temp { get; set; }
        public String hil_new_Owner_tempName { get; set; }
        public String hil_new_Owner_tempYomiName { get; set; }
        public EntityReference hil_newjobid { get; set; }
        public String hil_newjobidName { get; set; }
        public String hil_newserialnumber { get; set; }
        public EntityReference hil_NSH { get; set; }
        public String hil_NSHName { get; set; }
        public String hil_NSHYomiName { get; set; }
        public EntityReference hil_observation { get; set; }
        public String hil_observationName { get; set; }
        public EntityReference hil_OnBehalfofDealer { get; set; }
        public String hil_OnBehalfofDealerName { get; set; }
        public String hil_OnBehalfofDealerYomiName { get; set; }
        public int hil_OnHoldTime { get; set; }
        public DateTime hil_OverriddenCreatedOn { get; set; }
        public EntityReference hil_OwnerAccount { get; set; }
        public EntityReference hil_ownerid { get; set; }
        public String hil_OwnerAccountName { get; set; }
        public String hil_OwnerAccountYomiName { get; set; }
        public EntityReference hil_owningbusinessunit { get; set; }
        public String hil_owningbusinessunitName { get; set; }
        public EntityReference hil_owningteam { get; set; }
        public String hil_owningteamName { get; set; }
        public String hil_owningteamYomiName { get; set; }
        public EntityReference hil_owninguser { get; set; }
        public String hil_owninguserName { get; set; }
        public String hil_owninguserYomiName { get; set; }
        public Boolean hil_PaymentLinkSent { get; set; }
        public OptionSetValue hil_PaymentStatus { get; set; }
        public int hil_PendingQuantity { get; set; }
        public int hil_PhoneCallCount { get; set; }
        public EntityReference hil_pincode { get; set; }
        public String hil_pincodeName { get; set; }
        public String hil_PinCodeText { get; set; }
        public int hil_PMSCount { get; set; }
        public DateTime hil_pmsdate { get; set; }
        public String hil_PostalCode { get; set; }
        public DateTime hil_PreferredDate { get; set; }
        public OptionSetValue hil_PreferredTime { get; set; }
        public DateTime hil_PreferredTimeofVisit { get; set; }
        public String hil_PrimaryIncidentDescription { get; set; }
        public int hil_PrimaryIncidentEstimatedDuration { get; set; }
        public String hil_PRNo { get; set; }
        public String hil_PRNumberText { get; set; }
        public Guid hil_processid { get; set; }
        public EntityReference hil_Productcategory { get; set; }
        public String hil_ProductcategoryName { get; set; }
        public EntityReference hil_ProductCatSubCatMapping { get; set; }
        public String hil_ProductCatSubCatMappingName { get; set; }
        public EntityReference hil_ProductSubcategory { get; set; }
        public String hil_ProductSubcategoryName { get; set; }
        public int hil_quantity { get; set; }
        public int hil_quantityofunits { get; set; }
        public EntityReference hil_ReassignReason { get; set; }
        public String hil_ReassignReasonIncaseofOthers { get; set; }
        public String hil_ReassignReasonName { get; set; }
        public Decimal hil_receiptamount { get; set; }
        public Decimal hil_receiptamount_Base { get; set; }
        public String hil_receiptnumber { get; set; }
        public String hil_ReceiptsAmountInWords { get; set; }
        public EntityReference hil_RegardingEmail { get; set; }
        public String hil_RegardingEmailName { get; set; }
        public EntityReference hil_RegardingFallback { get; set; }
        public String hil_RegardingFallbackName { get; set; }
        public EntityReference hil_Region { get; set; }
        public String hil_RegionName { get; set; }
        public DateTime hil_RemainderCount_Date { get; set; }
        public int hil_RemainderCount_State { get; set; }
        public OptionSetValue hil_RequestType { get; set; }
        public Boolean hil_ResendPaymentLink { get; set; }
        public EntityReference hil_ResolveByKPI { get; set; }
        public String hil_ResolveByKPIName { get; set; }
        public Boolean hil_ReviewforCountryClassification { get; set; }
        public EntityReference hil_SalesOffice { get; set; }
        public String hil_SalesOfficeName { get; set; }
        public OptionSetValue hil_salutation { get; set; }
        public EntityReference hil_SchemeCode { get; set; }
        public String hil_SchemeCodeName { get; set; }
        public EntityReference hil_ServiceAddress { get; set; }
        public String hil_ServiceAddressName { get; set; }
        public EntityReference hil_slainvokedid { get; set; }
        public String hil_slainvokedidName { get; set; }
        public OptionSetValue hil_SourceofJob { get; set; }
        public Boolean hil_SparePartUse { get; set; }
        public Guid hil_stageid { get; set; }
        public EntityReference hil_state { get; set; }
        public OptionSetValue hil_statecode { get; set; }
        public String hil_stateName { get; set; }
        public String hil_StateOrProvince { get; set; }
        public Decimal hil_SubtotalAmount { get; set; }
        public Decimal hil_subtotalamount_Base { get; set; }
        public String hil_SystemRemarks { get; set; }
        public EntityReference hil_TATAchievementSlab { get; set; }
        public String hil_TATAchievementSlabName { get; set; }
        public EntityReference hil_TATCategory { get; set; }
        public String hil_TATCategoryName { get; set; }
        public DateTime hil_tattime { get; set; }
        public Boolean hil_Taxable { get; set; }
        public String hil_TermsConditions { get; set; }
        public DateTime hil_TimeClosed { get; set; }
        public DateTime hil_TimeFromPromised { get; set; }
        public DateTime hil_TimeToPromised { get; set; }
        public DateTime hil_TimeWindowEnd { get; set; }
        public DateTime hil_TimeWindowStart { get; set; }
        public int hil_TimeZoneRuleVersionNumber { get; set; }
        public Decimal hil_TotalAmount { get; set; }
        public Decimal hil_totalamount_Base { get; set; }
        public Decimal hil_TotalSalesTax { get; set; }
        public Decimal hil_totalsalestax_Base { get; set; }
        public EntityReference hil_town { get; set; }
        public String hil_townName { get; set; }
        public String hil_traversedpath { get; set; }
        public EntityReference hil_typeofassignee { get; set; }
        public String hil_typeofassigneeName { get; set; }
        public EntityReference hil_UnitWarranty { get; set; }
        public String hil_UnitWarrantyName { get; set; }
        public int hil_UTCConversionTimeZoneCode { get; set; }
        public Decimal hil_VersionNumber { get; set; }
        public DateTime hil_WarrantyDate { get; set; }
        public OptionSetValue hil_WarrantyStatus { get; set; }
        public OptionSetValue hil_WarrantySubStatus { get; set; }
        public EntityReference hil_WorkDoneBy { get; set; }
        public String hil_WorkDoneByName { get; set; }
        public String hil_WorkDoneByYomiName { get; set; }
        public String hil_WorkOrderSummary { get; set; }
        public EntityReference msdyn_agreement { get; set; }
        public String msdyn_agreementName { get; set; }
        public String msdyn_AutoNumbering { get; set; }
        public EntityReference msdyn_billingaccount { get; set; }
        public String msdyn_billingaccountName { get; set; }
        public String msdyn_billingaccountYomiName { get; set; }
        public String msdyn_BookingSummary { get; set; }
        public EntityReference msdyn_closedby { get; set; }
        public String msdyn_closedbyName { get; set; }
        public String msdyn_closedbyYomiName { get; set; }
        public DateTime msdyn_completedon { get; set; }
        public EntityReference msdyn_customerasset { get; set; }
        public String msdyn_customerassetName { get; set; }
        public Decimal msdyn_EstimateSubtotalAmount { get; set; }
        public Decimal msdyn_estimatesubtotalamount_Base { get; set; }
        public DateTime msdyn_firstarrivedon { get; set; }
        public String msdyn_FollowUpNote { get; set; }
        public Boolean msdyn_FollowUpRequired { get; set; }
        public EntityReference msdyn_FunctionalLocation { get; set; }
        public String msdyn_FunctionalLocationName { get; set; }
        public String msdyn_Instructions { get; set; }
        public String msdyn_InternalFlags { get; set; }
        public EntityReference msdyn_IoTAlert { get; set; }
        public String msdyn_IoTAlertName { get; set; }
        public String msdyn_name { get; set; }
        public EntityReference msdyn_opportunityid { get; set; }
        public String msdyn_opportunityidName { get; set; }
        public EntityReference msdyn_parentworkorder_msdyn_workorder { get; set; }
        public String msdyn_parentworkorder_msdyn_workorderName { get; set; }
        public EntityReference msdyn_preferredresource { get; set; }
        public String msdyn_preferredresourceName { get; set; }
        public EntityReference msdyn_pricelist { get; set; }
        public String msdyn_pricelistName { get; set; }
        public String msdyn_PrimaryIncidentDescription { get; set; }
        public int msdyn_PrimaryIncidentEstimatedDuration { get; set; }
        public EntityReference msdyn_primaryincidenttype { get; set; }
        public String msdyn_primaryincidenttypeName { get; set; }
        public EntityReference msdyn_PrimaryResolution { get; set; }
        public String msdyn_PrimaryResolutionName { get; set; }
        public EntityReference msdyn_priority { get; set; }
        public String msdyn_priorityName { get; set; }
        public EntityReference msdyn_reportedbycontact { get; set; }
        public String msdyn_reportedbycontactName { get; set; }
        public String msdyn_reportedbycontactYomiName { get; set; }
        public EntityReference msdyn_serviceaccount { get; set; }
        public String msdyn_serviceaccountName { get; set; }
        public String msdyn_serviceaccountYomiName { get; set; }
        public EntityReference msdyn_servicerequest { get; set; }
        public String msdyn_servicerequestName { get; set; }
        public EntityReference msdyn_serviceterritory { get; set; }
        public String msdyn_serviceterritoryName { get; set; }
        public EntityReference msdyn_substatus { get; set; }
        public String msdyn_substatusName { get; set; }
        public Decimal msdyn_SubtotalAmount { get; set; }
        public Decimal msdyn_subtotalamount_Base { get; set; }
        public EntityReference msdyn_SupportContact { get; set; }
        public String msdyn_SupportContactName { get; set; }
        public OptionSetValue msdyn_SystemStatus { get; set; }
        public Boolean msdyn_Taxable { get; set; }
        public EntityReference msdyn_taxcode { get; set; }
        public String msdyn_taxcodeName { get; set; }
        public DateTime msdyn_TimeClosed { get; set; }
        public DateTime msdyn_TimeFromPromised { get; set; }
        public EntityReference msdyn_timegroup { get; set; }
        public EntityReference msdyn_timegroupdetailselected { get; set; }
        public String msdyn_timegroupdetailselectedName { get; set; }
        public String msdyn_timegroupName { get; set; }
        public DateTime msdyn_TimeToPromised { get; set; }
        public Decimal msdyn_TotalAmount { get; set; }
        public Decimal msdyn_totalamount_Base { get; set; }
        public int msdyn_totalestimatedduration { get; set; }
        public Decimal msdyn_TotalSalesTax { get; set; }
        public Decimal msdyn_totalsalestax_Base { get; set; }
        public EntityReference msdyn_workhourtemplate { get; set; }
        public String msdyn_workhourtemplateName { get; set; }
        public EntityReference msdyn_workorderarrivaltimekpiid { get; set; }
        public String msdyn_workorderarrivaltimekpiidName { get; set; }
        public EntityReference msdyn_workorderresolutionkpiid { get; set; }
        public String msdyn_workorderresolutionkpiidName { get; set; }
        public String msdyn_WorkOrderSummary { get; set; }
        public EntityReference msdyn_workordertype { get; set; }
        public String msdyn_workordertypeName { get; set; }

    }
    public class dtoWorkOrderService
    {
        public string createdby { get; set; }
        public string createdbyname { get; set; }
        public string createdbyyominame { get; set; }
        public string createdon { get; set; }
        public string msdyn_workorderserviceid { get; set; }
        public string createdonbehalfby { get; set; }
        public string createdonbehalfbyname { get; set; }
        public string createdonbehalfbyyominame { get; set; }
        public string exchangerate { get; set; }
        public string hil_availabilitystatus { get; set; }
        public string hil_availabilitystatusname { get; set; }
        public string hil_chargeableornot { get; set; }
        public string hil_chargeableornotname { get; set; }
        public string hil_checkavailability { get; set; }
        public string hil_checkavailabilityname { get; set; }
        public string hil_defectiveserialnumber { get; set; }
        public string hil_delinkpo { get; set; }
        public string hil_delinkponame { get; set; }
        public string hil_discountedamount { get; set; }
        public string hil_effectiveamount { get; set; }
        public string hil_finalamount { get; set; }
        public string hil_isserialized { get; set; }
        public string hil_isserializedname { get; set; }
        public string hil_iswarrantyvoid { get; set; }
        public string hil_iswarrantyvoidname { get; set; }
        public string hil_linestatus { get; set; }
        public string hil_linestatusname { get; set; }
        public string hil_markused { get; set; }
        public string hil_markusedname { get; set; }
        public string hil_maxquantity { get; set; }
        public string hil_part { get; set; }
        public string hil_partamount { get; set; }
        public string hil_pendingquantity { get; set; }
        public string hil_priority { get; set; }
        public string hil_purchaseorder { get; set; }
        public string hil_purchaseordername { get; set; }
        public string hil_quantity { get; set; }
        public string hil_regardingestimate { get; set; }
        public string hil_regardingestimatename { get; set; }
        public string hil_replacedpart { get; set; }
        public string hil_replacedpartdescription { get; set; }
        public string hil_replacedpartname { get; set; }
        public string hil_replacedserialnumber { get; set; }
        public string hil_replacesamepart { get; set; }
        public string hil_replacesamepartname { get; set; }
        public string hil_returned { get; set; }
        public string hil_returnedname { get; set; }
        public string hil_totalamount { get; set; }
        public string hil_warrantystatus { get; set; }
        public string hil_warrantystatusname { get; set; }
        public string hil_warrantyvoidreason { get; set; }
        public string hil_warrantyvoidreasonname { get; set; }
        public string importsequencenumber { get; set; }
        public string modifiedby { get; set; }
        public string modifiedbyname { get; set; }
        public string modifiedbyyominame { get; set; }
        public string modifiedon { get; set; }
        public string modifiedonbehalfby { get; set; }
        public string modifiedonbehalfbyname { get; set; }
        public string modifiedonbehalfbyyominame { get; set; }
        public string msdyn_additionalcost { get; set; }
        public string msdyn_additionalcost_base { get; set; }
        public string msdyn_agreementbookingproduct { get; set; }
        public string msdyn_agreementbookingproductname { get; set; }
        public string msdyn_allocated { get; set; }
        public string msdyn_allocatedname { get; set; }
        public string msdyn_booking { get; set; }
        public string msdyn_bookingname { get; set; }
        public string msdyn_commissioncosts { get; set; }
        public string msdyn_commissioncosts_base { get; set; }
        public string msdyn_customerasset { get; set; }
        public string msdyn_customerassetname { get; set; }
        public string msdyn_description { get; set; }
        public string msdyn_discountamount { get; set; }
        public string msdyn_discountamount_base { get; set; }
        public string msdyn_discountpercent { get; set; }
        public string msdyn_estimatediscountamount { get; set; }
        public string msdyn_estimatediscountamount_base { get; set; }
        public string msdyn_estimatediscountpercent { get; set; }
        public string msdyn_estimatequantity { get; set; }
        public string msdyn_estimatesubtotal { get; set; }
        public string msdyn_estimatesubtotal_base { get; set; }
        public string msdyn_estimatetotalamount { get; set; }
        public string msdyn_estimatetotalamount_base { get; set; }
        public string msdyn_estimatetotalcost { get; set; }
        public string msdyn_estimatetotalcost_base { get; set; }
        public string msdyn_estimateunitamount { get; set; }
        public string msdyn_estimateunitamount_base { get; set; }
        public string msdyn_estimateunitcost { get; set; }
        public string msdyn_estimateunitcost_base { get; set; }
        public string msdyn_internaldescription { get; set; }
        public string msdyn_internalflags { get; set; }
        public string msdyn_lineorder { get; set; }
        public string msdyn_linestatus { get; set; }
        public string msdyn_linestatusname { get; set; }
        public string msdyn_name { get; set; }
        public string msdyn_pricelist { get; set; }
        public string msdyn_pricelistname { get; set; }
        public string msdyn_product { get; set; }
        public string msdyn_productname { get; set; }
        public string msdyn_purchaseorderreceiptproduct { get; set; }
        public string msdyn_purchaseorderreceiptproductname { get; set; }
        public string msdyn_qtytobill { get; set; }
        public string msdyn_quantity { get; set; }
        public string msdyn_subtotal { get; set; }
        public string msdyn_subtotal_base { get; set; }
        public string msdyn_taxable { get; set; }
        public string msdyn_taxablename { get; set; }
        public string msdyn_totalamount { get; set; }
        public string msdyn_totalamount_base { get; set; }
        public string msdyn_totalcost { get; set; }
        public string msdyn_totalcost_base { get; set; }
        public string msdyn_unit { get; set; }
        public string msdyn_unitamount { get; set; }
        public string msdyn_unitamount_base { get; set; }
        public string msdyn_unitcost { get; set; }
        public string msdyn_unitcost_base { get; set; }
        public string msdyn_unitname { get; set; }
        public string msdyn_warehouse { get; set; }
        public string msdyn_warehousename { get; set; }
        public string msdyn_workorder { get; set; }
        public string msdyn_workorderincident { get; set; }
        public string msdyn_workorderincidentname { get; set; }
        public string msdyn_workordername { get; set; }
        public string msdyn_workorderproductid { get; set; }
        public string overriddencreatedon { get; set; }
        public string ownerid { get; set; }
        public string owneridname { get; set; }
        public string owneridtype { get; set; }
        public string owneridyominame { get; set; }
        public string owningbusinessunit { get; set; }
        public string owningteam { get; set; }
        public string owninguser { get; set; }
        public string statecode { get; set; }
        public string statecodename { get; set; }
        public string statuscode { get; set; }
        public string statuscodename { get; set; }
        public string timezoneruleversionnumber { get; set; }
        public string transactioncurrencyid { get; set; }
        public string transactioncurrencyidname { get; set; }
        public string utcconversiontimezonecode { get; set; }
        public string versionnumber { get; set; }
        public string CreatedDateWH { get; set; }

    }
    public class dtoWorkorderProduct
    {
        public string createdby { get; set; }
        public string createdbyname { get; set; }
        public string createdbyyominame { get; set; }
        public DateTime? createdon { get; set; }
        public string createdonbehalfby { get; set; }
        public string createdonbehalfbyname { get; set; }
        public string createdonbehalfbyyominame { get; set; }
        public double? exchangerate { get; set; }
        public int? hil_availabilitystatus { get; set; }
        public string hil_availabilitystatusname { get; set; }
        public string hil_chargeableornot { get; set; }
        public string hil_chargeableornotname { get; set; }
        public bool? hil_checkavailability { get; set; }
        public string hil_checkavailabilityname { get; set; }
        public string hil_defectiveserialnumber { get; set; }
        public bool? hil_delinkpo { get; set; }
        public string hil_delinkponame { get; set; }
        public double? hil_discountedamount { get; set; }
        public double? hil_effectiveamount { get; set; }
        public double? hil_finalamount { get; set; }
        public int? hil_isserialized { get; set; }
        public string hil_isserializedname { get; set; }
        public bool? hil_iswarrantyvoid { get; set; }
        public string hil_iswarrantyvoidname { get; set; }
        public int? hil_linestatus { get; set; }
        public string hil_linestatusname { get; set; }
        public bool? hil_markused { get; set; }
        public string hil_markusedname { get; set; }
        public double? hil_maxquantity { get; set; }
        public string hil_part { get; set; }
        public double? hil_partamount { get; set; }
        public int? hil_pendingquantity { get; set; }
        public string hil_priority { get; set; }
        public string hil_purchaseorder { get; set; }
        public string hil_purchaseordername { get; set; }
        public double? hil_quantity { get; set; }
        public string hil_regardingestimate { get; set; }
        public string hil_regardingestimatename { get; set; }
        public string hil_replacedpart { get; set; }
        public string hil_replacedpartdescription { get; set; }
        public string hil_replacedpartname { get; set; }
        public string hil_replacedserialnumber { get; set; }
        public bool? hil_replacesamepart { get; set; }
        public string hil_replacesamepartname { get; set; }
        public int? hil_returned { get; set; }
        public string hil_returnedname { get; set; }
        public double? hil_totalamount { get; set; }
        public int? hil_warrantystatus { get; set; }  //
        public string hil_warrantystatusname { get; set; }
        public string hil_warrantyvoidreason { get; set; }
        public string hil_warrantyvoidreasonname { get; set; }
        public int? importsequencenumber { get; set; }
        public string modifiedby { get; set; }
        public string modifiedbyname { get; set; }
        public string modifiedbyyominame { get; set; }
        public DateTime? modifiedon { get; set; }
        public string modifiedonbehalfby { get; set; }
        public string modifiedonbehalfbyname { get; set; }
        public string modifiedonbehalfbyyominame { get; set; }
        public double? msdyn_additionalcost { get; set; }
        public double? msdyn_additionalcost_base { get; set; }
        public string msdyn_agreementbookingproduct { get; set; }
        public string msdyn_agreementbookingproductname { get; set; }
        public bool? msdyn_allocated { get; set; }
        public string msdyn_allocatedname { get; set; }
        public string msdyn_booking { get; set; }
        public string msdyn_bookingname { get; set; }
        public double? msdyn_commissioncosts { get; set; }
        public double? msdyn_commissioncosts_base { get; set; }
        public string msdyn_customerasset { get; set; }
        public string msdyn_customerassetname { get; set; }
        public string msdyn_description { get; set; }
        public double? msdyn_discountamount { get; set; }
        public double? msdyn_discountamount_base { get; set; }
        public float? msdyn_discountpercent { get; set; }
        public double? msdyn_estimatediscountamount { get; set; }
        public double? msdyn_estimatediscountamount_base { get; set; }
        public float? msdyn_estimatediscountpercent { get; set; }
        public float? msdyn_estimatequantity { get; set; }
        public double? msdyn_estimatesubtotal { get; set; }
        public double? msdyn_estimatesubtotal_base { get; set; }
        public double? msdyn_estimatetotalamount { get; set; }
        public double? msdyn_estimatetotalamount_base { get; set; }
        public double? msdyn_estimatetotalcost { get; set; }
        public double? msdyn_estimatetotalcost_base { get; set; }
        public double? msdyn_estimateunitamount { get; set; }
        public double? msdyn_estimateunitamount_base { get; set; }
        public double? msdyn_estimateunitcost { get; set; }
        public double? msdyn_estimateunitcost_base { get; set; }
        public string msdyn_internaldescription { get; set; }
        public string msdyn_internalflags { get; set; }
        public int? msdyn_lineorder { get; set; }
        public int? msdyn_linestatus { get; set; }
        public string msdyn_linestatusname { get; set; }
        public string msdyn_name { get; set; }
        public string msdyn_pricelist { get; set; }
        public string msdyn_pricelistname { get; set; }
        public string msdyn_product { get; set; }
        public string msdyn_productname { get; set; }
        public string msdyn_purchaseorderreceiptproduct { get; set; }
        public string msdyn_purchaseorderreceiptproductname { get; set; }
        public float? msdyn_qtytobill { get; set; }
        public float? msdyn_quantity { get; set; }
        public double? msdyn_subtotal { get; set; }
        public double? msdyn_subtotal_base { get; set; }
        public bool? msdyn_taxable { get; set; }
        public string msdyn_taxablename { get; set; }
        public double? msdyn_totalamount { get; set; }
        public double? msdyn_totalamount_base { get; set; }
        public double? msdyn_totalcost { get; set; }
        public double? msdyn_totalcost_base { get; set; }
        public string msdyn_unit { get; set; }
        public double? msdyn_unitamount { get; set; }
        public double? msdyn_unitamount_base { get; set; }
        public double? msdyn_unitcost { get; set; }
        public double? msdyn_unitcost_base { get; set; }
        public string msdyn_unitname { get; set; }
        public string msdyn_warehouse { get; set; }
        public string msdyn_warehousename { get; set; }
        public string msdyn_workorder { get; set; }
        public string msdyn_workorderincident { get; set; }
        public string msdyn_workorderincidentname { get; set; }
        public string msdyn_workordername { get; set; }
        public string msdyn_workorderproductid { get; set; }
        public DateTime? overriddencreatedon { get; set; }
        public string ownerid { get; set; }
        public string owneridname { get; set; }
        public string owneridtype { get; set; }
        public string owneridyominame { get; set; }
        public string owningbusinessunit { get; set; }
        public string owningteam { get; set; }
        public string owninguser { get; set; }
        public int? statecode { get; set; }
        public string statecodename { get; set; }
        public int? statuscode { get; set; }
        public string statuscodename { get; set; }
        public int? timezoneruleversionnumber { get; set; }
        public string transactioncurrencyid { get; set; }
        public string transactioncurrencyidname { get; set; }
        public int? utcconversiontimezonecode { get; set; }
        public Int64? versionnumber { get; set; }
        public DateTime? CreatedDateWH { get; set; }


    }
    public class WorkOrderServiceRequest
    {
        public string WorkOrderID { get; set; }
        public string WorkOrderServiceID { get; set; }
        public string WorkOrderIncidentID { get; set; }
    }
    public class WorkOrderServiceResponse
    {
        public List<dtoWorkOrderService> orderService { get; set; }
        public bool success { get; set; }
        public string error { get; set; }
    }
    public class WorkOrderProductRequest
    {
        public string WorkOrderID { get; set; }
        public string WorkOrderProductID { get; set; }
        public string WorkOrderIncidentID { get; set; }
    }
    public class WorkOrderProductResponse
    {
        public List<dtoWorkorderProduct> orderProduct { get; set; }
        public bool success { get; set; }
        public string error { get; set; }
    }
}
