using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Havells.D365.Entities.WorkorderProduct.Entity
{
    public class dtoWorkorderProduct
    {
        public string createdby { get; set; }
        public string createdbyname { get; set; }
        public string createdbyyominame { get; set; }
        public string createdon { get; set; }
        public string createdonbehalfby { get; set; }
        public string createdonbehalfbyname { get; set; }
        public string createdonbehalfbyyominame { get; set; }
        public string exchangerate { get; set; }
        public string hil_availabilitystatus { get; set; }
        public string hil_availabilitystatusname { get; set; }
        public string hil_chargeableornot { get; set; }
        public string hil_chargeableornotname { get; set; }
        public string hil_checkavailability { get; set; }
        public string hil_checkavailabilityname { get; set; }
        public string hil_defectiveserialnumber { get; set; }
        public string hil_delinkpo { get; set; }
        public string hil_delinkponame { get; set; }
        public string hil_discountedamount { get; set; }
        public string hil_effectiveamount { get; set; }
        public string hil_finalamount { get; set; }
        public string hil_isserialized { get; set; }
        public string hil_isserializedname { get; set; }
        public string hil_iswarrantyvoid { get; set; }
        public string hil_iswarrantyvoidname { get; set; }
        public string hil_linestatus { get; set; }
        public string hil_linestatusname { get; set; }
        public string hil_markused { get; set; }
        public string hil_markusedname { get; set; }
        public string hil_maxquantity { get; set; }
        public string hil_part { get; set; }
        public string hil_partamount { get; set; }
        public string hil_pendingquantity { get; set; }
        public string hil_priority { get; set; }
        public string hil_purchaseorder { get; set; }
        public string hil_purchaseordername { get; set; }
        public string hil_quantity { get; set; }
        public string hil_regardingestimate { get; set; }
        public string hil_regardingestimatename { get; set; }
        public string hil_replacedpart { get; set; }
        public string hil_replacedpartdescription { get; set; }
        public string hil_replacedpartname { get; set; }
        public string hil_replacedserialnumber { get; set; }
        public string hil_replacesamepart { get; set; }
        public string hil_replacesamepartname { get; set; }
        public string hil_returned { get; set; }
        public string hil_returnedname { get; set; }
        public string hil_totalamount { get; set; }
        public string hil_warrantystatus { get; set; }
        public string hil_warrantystatusname { get; set; }
        public string hil_warrantyvoidreason { get; set; }
        public string hil_warrantyvoidreasonname { get; set; }
        public string importsequencenumber { get; set; }
        public string modifiedby { get; set; }
        public string modifiedbyname { get; set; }
        public string modifiedbyyominame { get; set; }
        public string modifiedon { get; set; }
        public string modifiedonbehalfby { get; set; }
        public string modifiedonbehalfbyname { get; set; }
        public string modifiedonbehalfbyyominame { get; set; }
        public string msdyn_additionalcost { get; set; }
        public string msdyn_additionalcost_base { get; set; }
        public string msdyn_agreementbookingproduct { get; set; }
        public string msdyn_agreementbookingproductname { get; set; }
        public string msdyn_allocated { get; set; }
        public string msdyn_allocatedname { get; set; }
        public string msdyn_booking { get; set; }
        public string msdyn_bookingname { get; set; }
        public string msdyn_commissioncosts { get; set; }
        public string msdyn_commissioncosts_base { get; set; }
        public string msdyn_customerasset { get; set; }
        public string msdyn_customerassetname { get; set; }
        public string msdyn_description { get; set; }
        public string msdyn_discountamount { get; set; }
        public string msdyn_discountamount_base { get; set; }
        public string msdyn_discountpercent { get; set; }
        public string msdyn_estimatediscountamount { get; set; }
        public string msdyn_estimatediscountamount_base { get; set; }
        public string msdyn_estimatediscountpercent { get; set; }
        public string msdyn_estimatequantity { get; set; }
        public string msdyn_estimatesubtotal { get; set; }
        public string msdyn_estimatesubtotal_base { get; set; }
        public string msdyn_estimatetotalamount { get; set; }
        public string msdyn_estimatetotalamount_base { get; set; }
        public string msdyn_estimatetotalcost { get; set; }
        public string msdyn_estimatetotalcost_base { get; set; }
        public string msdyn_estimateunitamount { get; set; }
        public string msdyn_estimateunitamount_base { get; set; }
        public string msdyn_estimateunitcost { get; set; }
        public string msdyn_estimateunitcost_base { get; set; }
        public string msdyn_internaldescription { get; set; }
        public string msdyn_internalflags { get; set; }
        public string msdyn_lineorder { get; set; }
        public string msdyn_linestatus { get; set; }
        public string msdyn_linestatusname { get; set; }
        public string msdyn_name { get; set; }
        public string msdyn_pricelist { get; set; }
        public string msdyn_pricelistname { get; set; }
        public string msdyn_product { get; set; }
        public string msdyn_productname { get; set; }
        public string msdyn_purchaseorderreceiptproduct { get; set; }
        public string msdyn_purchaseorderreceiptproductname { get; set; }
        public string msdyn_qtytobill { get; set; }
        public string msdyn_quantity { get; set; }
        public string msdyn_subtotal { get; set; }
        public string msdyn_subtotal_base { get; set; }
        public string msdyn_taxable { get; set; }
        public string msdyn_taxablename { get; set; }
        public string msdyn_totalamount { get; set; }
        public string msdyn_totalamount_base { get; set; }
        public string msdyn_totalcost { get; set; }
        public string msdyn_totalcost_base { get; set; }
        public string msdyn_unit { get; set; }
        public string msdyn_unitamount { get; set; }
        public string msdyn_unitamount_base { get; set; }
        public string msdyn_unitcost { get; set; }
        public string msdyn_unitcost_base { get; set; }
        public string msdyn_unitname { get; set; }
        public string msdyn_warehouse { get; set; }
        public string msdyn_warehousename { get; set; }
        public string msdyn_workorder { get; set; }
        public string msdyn_workorderincident { get; set; }
        public string msdyn_workorderincidentname { get; set; }
        public string msdyn_workordername { get; set; }
        public string msdyn_workorderproductid { get; set; }
        public string overriddencreatedon { get; set; }
        public string ownerid { get; set; }
        public string owneridname { get; set; }
        public string owneridtype { get; set; }
        public string owneridyominame { get; set; }
        public string owningbusinessunit { get; set; }
        public string owningteam { get; set; }
        public string owninguser { get; set; }
        public string statecode { get; set; }
        public string statecodename { get; set; }
        public string statuscode { get; set; }
        public string statuscodename { get; set; }
        public string timezoneruleversionnumber { get; set; }
        public string transactioncurrencyid { get; set; }
        public string transactioncurrencyidname { get; set; }
        public string utcconversiontimezonecode { get; set; }
        public string versionnumber { get; set; }
        public string CreatedDateWH { get; set; }
    }
}
